### ISSUE TITLE
Extract cosmetics too long

### ISSUE THREAD

**Issue by IEXPECTATION** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#11] opened 2021-08-12 14:42 UTC
Hello, First of all, Thanks for your works. But I'm stuck with "Waiting for all Cosmetic Extraction to Finish" for a long time, when I perform "Inject all Actived ID's".
I use the database which software downloads.
How do I deal with this situation?

**Comment by AKA2320** [comment] 2021-08-13 16:09
> Hello, First of all, Thanks for your works. But I'm stuck with "Waiting for all Cosmetic Extraction to Finish" for a long time, when I perform "Inject all Actived ID's".
> I use the database which software downloads.
> How do I deal with this situation?

after doing some trial and error, i found that if you select the default style (style count 0) and not select miscellaneous, you are no longer stuck on that waiting error. But there is still a problem where ambient effects of almost all immortal sets are not being loaded up. is this a limitation of the tool or am i doing something wrong?

**Comment by XCongoAlpha** [comment] 2021-08-13 23:59
I've experienced the "Waiting for all Cosmetic Extraction to Finish" too. I left the PC overnight (~6Hrs) and it is still extracting. 
That is what happens when I use the downloaded Handy Injection Database by AJOM.

But if I make my own custom database from scratch, I don't face such issues.

>  i found that if you select the default style (style count 0) and not select miscellaneous, you are no longer stuck on that waiting error

You don't need limit yourself by doing that. If you use your own database, you won't face the "Waiting for all Cosmetic Extraction to Finish". If anyone got a better solution, please do tell.

>  ambient effects of almost all immortal sets are not being loaded up

It works fine on my end. Maybe a side effect of disabling misc? I don't know.

Make your own database (Dont  edit the downladed database, Make your own from scratch). I know its a lot of work but it the only solution I have found. Don't forget to save it for future edits and use.

**Comment by AKA2320** [comment] 2021-08-14 09:20
> But if I make my own custom database from scratch, I don't face such issues.

does that fix the issue of no particle/ambient effects with immortals?

**Comment by XCongoAlpha** [comment] 2021-08-14 23:21
> does that fix the issue of no particle/ambient effects with immortals?

First of all, this is the wrong thread to talk about missing effects. The topic is different here.
You could try it out yourself because it's fairly easy to do so. I havent faced immortals without the effects. Tell me which immortals doesnt have the effects and let me try it out.

1. Are you sure you are using the handy injection? Handy injection automatically connects the particles, skill image etc to the cosmetic.
2. Make sure that the auto shutnik method in the advanced settings is enabled.
3. Maybe you used a particle/effects removal mod like [No-Bing Dota](https://github.com/No-Bling/DOTA) or [Dota 2 No Hats Mod](https://nohatspreacher.wordpress.com/)

**Comment by ducbh62git** [comment] 2021-08-16 17:58
> > Hello, First of all, Thanks for your works. But I'm stuck with "Waiting for all Cosmetic Extraction to Finish" for a long time, when I perform "Inject all Actived ID's".
> > I use the database which software downloads.
> > How do I deal with this situation?
> 
> after doing some trial and error, i found that if you select the default style (style count 0) and not select miscellaneous, you are no longer stuck on that waiting error. But there is still a problem where ambient effects of almost all immortal sets are not being loaded up. is this a limitation of the tool or am i doing something wrong?
> 

I also fixed the error by this way but not all. Some arcanas are still working without selecting default style

**Comment by ducbh62git** [comment] 2021-08-16 18:17
I've done to add items for **all heroes** with making my own database. My output file is about 62 KB now. So the number of items is not problem.

I also met your error in some cases:
- Adding items for Dragon Knight (except new persona) 
- Change Monkey King Arcana style count
- Change Prismatic Grace style count(Naga Siren's weapon).

I also changed Phantom Assassin Arcana style count completely so style count feature is working but it gets stuck on some items.

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-08-17 14:58
There seems to be a bug on the PID indentification which was stated here. Thankfully I added a debugging messages below the GUI that pinpoints the problem regarding the infinite loop. The topic will be continued at #13

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-08-17 15:04
> But there is still a problem where ambient effects of almost all immortal sets are not being loaded up. is this a limitation of the tool or am i doing something wrong?

@AKA2320 go to **Steam\steamapps\common\dota 2 beta\game\dota\gameinfo.gi** then Upload it here.
gameinfo.gi is in charge of the ambient effects.

**Comment by AKA2320** [comment] 2021-08-18 06:44
> > But there is still a problem where ambient effects of almost all immortal sets are not being loaded up. is this a limitation of the tool or am i doing something wrong?
> 
> @AKA2320 go to **Steam\steamapps\common\dota 2 beta\game\dota\gameinfo.gi** then Upload it here.
> gameinfo.gi is in charge of the ambient effects.

Thank you for replying, i tried running the application with windows 8 compatibility and that seems to have fixed my issue. Maybe it was just a system bug

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-08-18 07:53
That's good to hear, What Windows OS do you use?

**Comment by AKA2320** [comment] 2021-08-18 08:21
> That's good to hear, What Windows OS do you use?

i am on windows 10 home

**Comment by IEXPECTATION** [comment] 2021-08-18 08:25
> That's good to hear, What Windows OS do you use?

I use the professional version of windows 10.

**Comment by IEXPECTATION** [comment] 2021-08-18 15:50
I run the latest version of the tool, but it popped up an error
![Screenshot 2021-08-18 214151](https://user-images.githubusercontent.com/40608137/129927521-053647b8-e9a0-40c2-ae35-86d7771ca605.png)

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-08-18 16:27
Try to Rerun, multiple times and see if it still persists.

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-08-21 02:29
The problem is now fixed.

Future problems regarding Infinite Loop will now be moved at #15

**Closed by Aldrin-John-Olaer-Manalansan** 2021-08-21 02:29 UTC
