### ISSUE TITLE
Some items make the tool stop working / animations problems ?

### ISSUE THREAD

**Issue by skyasha** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#10] opened 2021-07-24 02:41 UTC
Hello.

Some items (golden items, crimson items) make the tool stop working, also some arcanas (qop, wr) can't use the second "form" with other arcanas otherwise the tool stop working too.

All the spells the rubicks arcana can steal are also green / rubick form when used by the original heroes (invokers meteor ball is green, kunkkas ultimate is green, warlocks golems have the green halo / aura too)

Thank you in advance if you have any solution for these issues, itll be greatly appreciated !

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-07-25 10:13
I don't quite get what you mean about "the tool stopped working". But I guess what you meant was "the MOD is not functioning properly"

You might be talking about hero personas. Personas are actually new features right before the last updates. Up until now I am currently working on a way on stabilizing the persona cosmetics mod during gameplay. So yes, the mod currently is having limitations towards hero personas. My suggestion for you is to download a custom persona mod from other websites, then integrate it at the "External Files" by [watching this](https://www.youtube.com/watch?v=eG2XRCj7Sy0).

About Rubick's Arcana, I will implement in the future an option that allows the user to enable/disable particle file extraction.

I am not that free guy these days, so updating the tool might take a long time.

**Comment by skyasha** [comment] 2021-07-25 18:55
No worries brother, take your time.

And not, i wasnt talking about personas, but arcanas (Qops one, Wrs one mainly) and some items that cause the tool to create the pak folder indefinitely and i have to restart the tool to use it again.

Some items like i said, the golden staff of MK ou crimson head of Centaur make the same problem occur again.

Anyway thank you for replying and i was just giving a feedback, your works really amazing and i hope learning for you again, see ya buddy !

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-07-25 19:35
Give me a handy injection database file of your collection which makes the tool run indefinitely. I will test if it is tool related bug or client related bug.

Regarding to golden/crimson cosmetic items, I will furtherly investigate that problem. The skin bug It might have caused by new .vmat structure.

**Comment by skyasha** [comment] 2021-07-26 01:00
[Mods.zip](https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/files/6874854/Mods.zip)
Check this out, and tell me if it works, thank you !

**Comment by skyasha** [comment] 2021-08-03 19:24
Did you test it buddy ? Had it some problems for you too ?

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-08-03 22:18
Hello there, I conducted the test and the database generated the mod successfully. So it seems to be client sided(your windows OS problem) which I will furtherly investigate and simulate in the future. For now i wish for all persons experiencing the same problem to bear with it. It will be fixed in time.

**Comment by skyasha** [comment] 2021-08-03 22:52
Is it better to use with windows 8.1 or 10 ? Im using 10 actually.

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-08-03 23:22
I have tested the tool on windows 7, 8,  and 8.1 so far in the long run which works fine. I haven't tried testing the tool to mod dota 2 on windows 10.

**Comment by AKA2320** [comment] 2021-08-13 17:58
> Is it better to use with windows 8.1 or 10 ? Im using 10 actually.

did you find a solution to the ambient effects not showing up problem? E.g on centaur i have the crimson weapon but the weapon itself has no effects (looks dead), it does show the immortal animation in demo but it has no ability icon either.

**Comment by Aldrin-John-Olaer-Manalansan** [comment] 2021-08-18 02:29
> > Is it better to use with windows 8.1 or 10 ? Im using 10 actually.
> 
> did you find a solution to the ambient effects not showing up problem? E.g on centaur i have the crimson weapon but the weapon itself has no effects (looks dead), it does show the immortal animation in demo but it has no ability icon either.

Open using text editor steam/steamapps/common/dota 2 beta/game/dota/gameinfo.gi

Screenshot them and send it here.

**Closed** 2021-08-25 06:15 UTC
